export const active = (selector: string): string => `${selector}:active`;
export const after = (selector: string): string => `${selector}::after`;
export const before = (selector: string): string => `${selector}::before`;
export const checked = (selector: string): string => `${selector}:checked`;
export const disabled = (selector: string): string => `${selector}:disabled`;
export const enabled = (selector: string): string => `${selector}:enabled`;
export const even = (selector: string): string => `${selector}:nth-child(even)`;
export const first = (selector: string): string => `${selector}:first-child`;
export const focus = (selector: string): string => `${selector}:focus`;
export const focusVisible = (selector: string): string => `${selector}:focus-visible`;
export const focusWithin = (selector: string): string => `${selector}:focus-within`;
export const hover = (selector: string): string => `${selector}:hover`;
export const indeterminate = (selector: string): string => `${selector}:indeterminate`;
export const invalid = (selector: string): string => `${selector}:invalid`;
export const last = (selector: string): string => `${selector}:last-child`;
export const odd = (selector: string): string => `${selector}:nth-child(odd)`;
export const optional = (selector: string): string => `${selector}:optional`;
export const placeholder = (selector: string): string => `${selector}::placeholder`;
export const readOnly = (selector: string): string => `${selector}:read-only`;
export const readWrite = (selector: string): string => `${selector}:read-write`;
export const required = (selector: string): string => `${selector}:required`;
export const selection = (selector: string): string => `${selector}::selection, ${selector} ::selection`;
export const target = (selector: string): string => `${selector}:target`;
export const valid = (selector: string): string => `${selector}:valid`;
export const visited = (selector: string): string => `${selector}:visited`;

export const groupActive = (selector: string): string => `.group:active ${selector}`;
export const groupFocus = (selector: string): string => `.group:focus ${selector}`;
export const groupFocusWithin = (selector: string): string => `.group:focus-within ${selector}`;
export const groupHover = (selector: string): string => `.group:hover ${selector}`;
export const groupInvalid = (selector: string): string => `.group:invalid ${selector}`;
export const groupValid = (selector: string): string => `.group:valid ${selector}`;
