name: Lint, check, and test every commit and PR

on:
  pull_request:
    paths-ignore:
      - "projects/site/**"
  push:
    paths-ignore:
      - "projects/site/**"

jobs:
  lint-and-check:
    strategy:
      matrix:
        node-version: [18]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - run: pnpm install
      - run: pnpm run lint
      - run: pnpm -r run check
  
  test:
    needs: lint-and-check
    strategy:
      matrix:
        node-version: [14, 16, 18]
        os: [ubuntu-latest, windows-latest, macOS-latest]
        tailwindcss-version: ["^2", "^3"]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - run: pnpm install
      - run: cd projects/tailwindcss-theme-variants && pnpm install --save tailwindcss@${{ matrix.tailwindcss-version }}
      - run: pnpm -r run test
