name: Publish to NPM every tag (i.e. new version)

on:
  push:
    tags:
      - '*'

jobs:
  test:
    strategy:
      matrix:
        node-version: [12, 14]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/
      - uses: pnpm/action-setup@v1.2.0
        with:
          version: 5.6.x
      - run: pnpm install
      - run: pnpm run test
  
  publish:
    needs: test
    strategy:
      matrix:
        node-version: [14]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/
      - uses: pnpm/action-setup@v1.2.0
        with:
          version: 5.6.x
      - run: pnpm install
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
