name: Publish to NPM every tag (i.e. new version)

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    strategy:
      matrix:
        node-version: [14]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/
      - uses: pnpm/action-setup@v2.0.0
        with:
          version: 5.18.x
      - run: cd projects/tailwindcss-theme-variants && pnpm install
      - run: pnpm -r publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
